### ISSUE TITLE
Audio only mode

### ISSUE THREAD

**Issue by barfin** [aramg/droidcam#61]
i tried the latest version with sound support and it worked fantastic but if i don't wanna my phone's camera and only microphone i have to keep it on and it drains battery for no reason
an audio only mode would be fantastic

**Comment by aramg** [comment]
Added an option to separate a/v to droidcam-cli, would you mind giving it a try?
www.dev47apps.com/files/linux/droidcam_cli_12.zip

**Comment by barfin** [comment]
> Added an option to separate a/v to droidcam-cli, would you mind giving it a try?
> [www.dev47apps.com/files/linux/droidcam_cli_12.zip](http://www.dev47apps.com/files/linux/droidcam_cli_12.zip)

thanks i tried it and it worked the exact same way that what i was looking for
but one little tiny minor thing even though i was using audio only mode it still didn't work without loading up the 'v4l2loopback-dc' module first
which is quite useless when not using the webcam

**Comment by aramg** [comment]
Fair enough. 
The download is updated with changes to keep going even if video device is missing.

**Comment by barfin** [comment]
> Fair enough.
> The download is updated with changes to keep going even if video device is missing.

thanks for the update, it worked perfectly fine

**Comment by Whitecatkeke** [comment]
Works very well. Thanks very much. Just wondering if this feature can be also added to droidcam (GUI)?

**Comment by aramg** [comment]
Splitting the A/V in the GUI is _slightly_ more work, I'll try to do it after finishing the MacOS client.

**Comment by Whitecatkeke** [comment]
> Splitting the A/V in the GUI is _slightly_ more work, I'll try to do it after finishing the MacOS client.

Thanks very much.

**Comment by aramg** [comment]
Added separate audio/video toggles the GUI client, would love a conformation it works as expected:
https://www.dev47apps.com/files/linux/droidcam_v13.zip

**Comment by Whitecatkeke** [comment]
> Added separate audio/video toggles the GUI client, would love a conformation it works as expected:
> https://www.dev47apps.com/files/linux/droidcam_v13.zip

It works very well. Thank you very much.

**Comment by Whitecatkeke** [comment]
> Added separate audio/video toggles the GUI client, would love a conformation it works as expected:
> https://www.dev47apps.com/files/linux/droidcam_v13.zip

There seems to be a small problem. The connection is usually good for the first time. But if I click "stop" and click "connect" again, it says "audio connection reset". It seems I have to restart the Android app to make it work again.

**Comment by aramg** [comment]
You're right, good catch. Thats actually missing from the earlier cli update as well.
Fixed and updated the download zip. 
(Also compiled on older Ubuntu for broader support)

**Comment by Whitecatkeke** [comment]
> You're right, good catch. Thats actually missing from the earlier cli update as well.
> Fixed and updated the download zip.
> (Also compiled on older Ubuntu for broader support)

Thanks very much. Just had a test. The cli file seems okay, if the gap between two consecutive connections is larger than 3 seconds; the GUI is also working well with audio and video both on. However, if I choose audio only in the GUI, then "audio connection reset" still occurs.

**Comment by aramg** [comment]
Does the phone app switch back to idle when you Stop from the GUI client?
Ot does it keep showing the microphone view?

**Comment by Whitecatkeke** [comment]
> phone app switch back to idle

Thanks. The phone app switch back to idle when I click "stop" in the GUI. When I click connect again, the microphone view appears in the app for a second, then quickly revert back to idle, at this time,  "audio connection reset" pops up on the pc. This doesn't happen when video and audio are both on.

**Comment by aramg** [comment]
hmm, thats really strange. Seems to work OK for me when I re-connect over and over with audio only. Can you try rebooting the phone and see it changes anything. 
Also the cli with audio only works fine when you try connecting more than once?

**Comment by Whitecatkeke** [comment]
> hmm, thats really strange. Seems to work OK for me when I re-connect over and over with audio only. Can you try rebooting the phone and see it changes anything.
> Also the cli with audio only works fine when you try connecting more than once?

Thanks very much. For cli: "audio connection reset" will pop up if I reconnect to soon, say, if I disconnect and reconnect immediately. But the problem doesn't occur as long as I wait for a few seconds between the disconnect and reconnect, which is good enough for actual usage in practice. For the GUI, it is still the same behaviour, "audio connection reset" will pop up until I restart the app for 'audio only'. I checked this on two Pixel phones, and had the same result. So the problem might be my distro, which is Manjaro.

**Comment by aramg** [comment]
I don't think it's the client, something must be up on the phone side.
Any chance you can email me a logcat capture of when the second connection fails?
Run `adb logcat > /tmp/logcat.txt` and do the dual connect with the 2nd one failing. You can then double check /tmp/logcat.txt for any sensitive info, there shouldn't be any, and email me a zip.

**Comment by Whitecatkeke** [comment]
> I don't think it's the client, something must be up on the phone side.
> Any chance you can email me a logcat capture of when the second connection fails?
> Run `adb logcat > /tmp/logcat.txt` and do the dual connect with the 2nd one failing. You can then double check /tmp/logcat.txt for any sensitive info, there shouldn't be any, and email me a zip.

Thanks. Could you please tell me your email address?

**Comment by aramg** [comment]
> Thanks. Could you please tell me your email address?

dev47apps at gmail.com

**Comment by Whitecatkeke** [comment]
> > Thanks. Could you please tell me your email address?
> 
> dev47apps at gmail.com

Just let you know that I have sent you the logcat file.

**Comment by lollita** [comment]
Do it have audio only and a cli for windows?
